### ISSUE TITLE
Playbook will fail when controller and provisioner are the same host

### ISSUE THREAD

**Issue by rabin-io** [redhat-cip/dci-openshift-agent#12]
The code block here: https://github.com/redhat-cip/dci-openshift-agent/blob/5bd0c8a5a85ce27c77ff99a2556f97e326d0e2a2/plays/ipi-install.yml#L107-L142 will fail on this task:
```yaml
  - name: "Allow HTTP traffic"
    firewalld:
      port: "{{ aw_dynamic_port }}/tcp"
      permanent: false
      immediate: true
      state: enabled
      zone: "{{ aw_zone }}"
    become: true
    delegate_to: localhost
```
As `aw_zone` is not set because `lo` interface (the output of the route command before it) is not part of any firewalld zone.
